sudo: required

services:
  - docker

jobs:
  include:
    - stage: build
      script:
        - docker build -t $DOCKER_USERNAME/docker-openstack-client .
    - stage: deploy
      script:
        - docker build -t $DOCKER_USERNAME/docker-openstack-client .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push snieking/docker-openstack-client
      
stages:
  - name: build
  - name: deploy
    if: branch = master
